In [ ]:
!cat /proc/cpuinfo


processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo


MemTotal:       13290460 kB
MemFree:         7335940 kB
MemAvailable:   12011620 kB
Buffers:          384816 kB
Cached:          4433748 kB
SwapCached:            0 kB
Active:           679908 kB
Inactive:        4903196 kB
Active(anon):       1268 kB
Inactive(anon):   764888 kB
Active(file):     678640 kB
Inactive(file):  4138308 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               180 kB
Writeback:             0 kB
AnonPages:        764560 kB
Mapped:           340628 kB
Shmem:              1608 kB
KReclaimable:     184136 kB
Slab:             228068 kB
SReclaimable:     184136 kB
SUnreclaim:        43932 kB
KernelStack:        6060 kB
PageTables:        14640 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645228 kB
Committed_AS:    3019792 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12424 kB
VmallocChunk:    

#Basic data types


1.   Int
2.   float
3. str




In [ ]:
type(3)

int

In [ ]:
type(3.56)

float

In [ ]:
type('a')

str

In [ ]:
type('shfs')

str

#Constants & Variables

In [ ]:
a1,a2,a3="aadt","dfa","adff"
print(a1)
print(a2)
print(a3)

aadt
dfa
adff


#INput function

input is always taken as string

In [ ]:
num1=input("ENter the first number")
num2=input("Enter second number")

ENter the first number234
Enter second number"sfaf"


In [ ]:
print(num1)
print(num2)

234
"sfaf"


In [ ]:
a=input("Num1:")
b=input("Num2:")

sum=a+b
print(sum)

Num1:7
Num2:9
79


In [ ]:
sum2=float(a)+float(b)
print(sum2)

16.0


#Data Types





In [ ]:
#String

print("hello "*3)

hello hello hello 


In [ ]:
name="bfjdbiuerhvilvn"

print(name[2:7])

jdbiu


In [ ]:
#step
print(name[1:8:3])
#every third char from index 1(included)

fbe


#Types of Objects in Python:

Immutable Objects
Mutable Objects
Immutable Objects:

1.int
2.float
3.string
4.bool
5.tuple

Mutable Objects:

1.List
2.Set
3.Dictionary
4.List

List

In [ ]:
lst=[3,4,5,6,7]
print(lst)
type(lst)

[3, 4, 5, 6, 7]


list

In [ ]:
mylst=[2,4.67,"kshbvkj",'d',True]
print(mylst)

[2, 4.67, 'kshbvkj', 'd', True]


In [ ]:
mylst.append('SHiv')
print(mylst)

[2, 4.67, 'kshbvkj', 'd', True, 'SHiv', 'SHiv', 'SHiv']


In [ ]:
print(mylst)

[2, 4.67, 'kshbvkj', 'd', True, 'SHiv', 'SHiv', 'SHiv']


In [ ]:
del mylst[5]
print(mylst)

[2, 4.67, 'kshbvkj', 'd', True, 'SHiv', 'SHiv']


In [ ]:
ls1=[2,5,6,1,9,'sdf']
ls2=['dd',4,4.6]
print(ls1+ls2)

[2, 5, 6, 1, 9, 'sdf', 'dd', 4, 4.6]


In [ ]:
print(len(ls1+ls2))

9


Tuples

In [ ]:
#uses paranthesis
tuple_1=(2,'rf',4.6,2)
print(tuple_1)

(2, 'rf', 4.6, 2)


In [ ]:
#tuple to list or vice-versa

mlst=list(tuple_1)
print(tuple_1)
print(mlst)

(2, 'rf', 4.6, 2)
[2, 'rf', 4.6, 2]


Set

In [ ]:
#set--> in {}
#doesn't support indexing
#No duplicate values

st={2,5,"wda",True}
print(st)

{True, 2, 'wda', 5}


Dictionary

Key-Value Pair

In [ ]:
 #does not allow duplicates

 dic={
     "name":"Shiv",
     "age":21,
     "City":"Bangalore"
 }

 print(dic["age"])

21


membrship operator

In [ ]:
lst=[2,5,6,7,9,1]

a=8
b=6

print(a in lst)
print(b in lst)

False
True


In [ ]:
if(b>a):
    print("b great")
else:
  print("No")

No


for loop

In [ ]:
for i in range(5):
  st=int(input("Enter val "))

Enter val3
Enter val4
Enter val5
Enter val2
Enter val6


In [ ]:
print(st)


6


In [ ]:
lst=[]
for i in range(4):
  lst.append(int(input("Enter val:")))

Enter val:3
Enter val:5
Enter val:2
Enter val:6


In [ ]:
lst.insert(3,9)
print(lst)


[3, 5, 2, 9, 6]


In [ ]:
c=3
while c<6:
  print(c)
  c+=1

3
4
5


#NumPy

in normal list

In [ ]:
import numpy as np

In [ ]:
from time import process_time

lst=[i for i in range(1000)]

st_time=process_time()

lst=[i+5 for i in lst]

en_time=process_time()

print(en_time-st_time)


0.00021014100000016356


in numpy

In [ ]:
np_arr=np.array([i for i in range(1000)])

st=process_time()

np_arr+=5

et=process_time()

print(et-st)

0.0014920380000003064


In [ ]:
#2d array in np

arr=np.array([(1,2,3),(4,5,6)])
print(arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
#2d array of zero
arr2=np.zeros((5,6))
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
arr3=np.ones((5,6))
print(arr3)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#certain val
val=6
arr4=np.full((5,6),val)
print(arr4)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


In [ ]:
 #random matrix
ar=np.random.random((4,5))
print(ar)

[[0.00524476 0.58022943 0.60149976 0.56205228 0.70523704]
 [0.55152862 0.31472954 0.95929647 0.34380374 0.98122952]
 [0.56316187 0.96759915 0.80876938 0.53582222 0.66754364]
 [0.33454296 0.98840696 0.38904791 0.91921132 0.4115577 ]]


In [ ]:
ar=np.random.randint(1,25,(4,5))
print(ar)

[[ 7 18 21 19 20]
 [13  9 19 22 19]
 [10 23 22  1  4]
 [12  6  8  3 19]]


In [ ]:
#evenly spaces vals
c=np.linspace(10,66,5)
print(c)

[10. 24. 38. 52. 66.]


In [ ]:
 #stepping by some val
d=np.arange(10,66,5)
print(d)

[10 15 20 25 30 35 40 45 50 55 60 65]


In [ ]:
#list to np array
lst=[3,56,7,2,6]
np_arr=np.asarray(lst)
type(np_arr)
print(np_arr)

[ 3 56  7  2  6]


Analysing numpy array

In [ ]:
b=np.random.randint(2,9,(3,7))
print(b)
print()
print(b.shape)

[[8 6 5 2 8 8 4]
 [8 3 7 2 8 5 4]
 [6 8 4 8 4 8 3]]

(3, 7)


In [ ]:
#dimensions
print(b.ndim)

2


In [ ]:
#no of ele
print(b.size)

21


In [ ]:
#reshape matrix
b=np.random.randint(2,9,(4,8))
print(b)

c=b.reshape(2,16)
print(c)
print(c.shape)

[[8 2 8 2 6 4 2 8]
 [7 6 3 8 4 2 4 6]
 [3 8 8 5 3 3 3 5]
 [6 5 6 5 8 3 7 3]]
[[8 2 8 2 6 4 2 8 7 6 3 8 4 2 4 6]
 [3 8 8 5 3 3 3 5 6 5 6 5 8 3 7 3]]
(2, 16)


#Pandas library

Useful for data analysis and processing.

In [ ]:
import pandas as pd

Creaating pandas data frme

In [ ]:
!pip install matplotlib-venn

In [ ]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate


In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
lbc=load_breast_cancer()
print(lbc)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

Csv file to pandas dataframe

In [ ]:
diabets_df=pd.read_csv('/diabetes (1).csv')

In [ ]:
type(diabets_df)

pandas.core.frame.DataFrame

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
diabets_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
print(diabets_df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [ ]:
print(diabets_df.shape)

(768, 9)


Exporting a Dataframe to a csv file